name: pytest

on: [ pull_request ]

defaults:
  run:
    shell: bash

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: jettero/kersplat:1.0.21
    steps:

      - uses: actions/checkout@v2

      - name: install dependencies
        env:
          SKIP_0_POOL_NTP_TEST: "yeah!"
        run: |
          source /etc/profile.d/kersplat.sh
          which python
          which pip
          python --version
          pip --version
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          bash mk-requires.sh
          python -m pip install -r requirements.txt

      - name: run pytest
        run: |
          source /etc/profile.d/kersplat.sh
          python -m pytest tests
